### ISSUE TITLE
mysql: 如果在 filter clone 了 message，则报错 type:framework, code:121, msg:mysql client transport: ReqHead should be type of *mysql.Request

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-ecosystem/go-database#14]
### What version of trpc-go-database are you using?

`trpc.group/trpc-go/trpc-database/mysql v1.0.0`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE='on'
GOARCH='amd64'
GOBIN='/home/ubuntu/go/bin'
GOCACHE='/home/ubuntu/.cache/go-build'
GOENV='/home/ubuntu/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/ubuntu/go/pkg/mod'
GONOPROXY='github.com/Andrew-M-C'
GONOSUMDB='github.com/Andrew-M-C'
GOOS='linux'
GOPATH='/home/ubuntu/go'
GOPRIVATE='github.com/Andrew-M-C'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build899563689=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

正常通过 client db 获取是正常的，但是一旦在 client filter 中执行了 `codec.WithCloneMessage(ctx)`, 就会失败

### What did you expect to see?

`查询 DB 成功, 结果: [{5.7.18-txsql-log}]`

### What did you see instead?

`查询 DB 失败: type:framework, code:121, msg:mysql client transport: ReqHead should be type of *mysql.Request`

#### `main.go`:

```go
package main

import (
	"context"
	"fmt"

	"trpc.group/trpc-go/trpc-database/mysql"
	"trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/codec"
	"trpc.group/trpc-go/trpc-go/filter"
)

func main() {
	_ = trpc.NewServer()
	proxy := mysql.NewClientProxy("trpc.mysql.blahblah")
	var res []version
	err := proxy.Select(context.Background(), &res, "SELECT VERSION() AS version")
	if err != nil {
		fmt.Println("查询 DB 失败:", err)
		return
	}
	fmt.Println("查询 DB 成功, 结果:", res)
}

type version struct {
	Version string `db:"version"`
}

func init() {
	filter.Register("test_filter", serverFilter, clientFilter)
}

func serverFilter(ctx context.Context, req any, next filter.ServerHandleFunc) (rsp any, err error) {
	return next(ctx, req)
}

func clientFilter(ctx context.Context, req, rsp any, next filter.ClientHandleFunc) error {
	ctx, _ = codec.WithCloneMessage(ctx)
	// ... 其他操作 ...
	return next(ctx, req, rsp)
}
```

#### trpc_go.yaml

```yaml
client:
  filter:
    - test_filter
  service:
    - name: trpc.mysql.blahblah
      target: dsn://root:${password}(${ip}:3306)/db_test?timeout=1s&parseTime=true
```

**Comment by Leoyoungxh** [comment]
Because `codec.WithCloneMessage` does not copy all fileds from the source message, it may result in the loss of some fields. You should use `codec.CopyMsg` copy all fields from the source message to the destination message.

By the way, why use `WithCloneMessage` in the filter? The framework can not directly use the context retured by `WithCloneMessage`.

Maybe you can use origin context instead.

```golang
func clientFilter(ctx context.Context, req, rsp any, next filter.ClientHandleFunc) error {
	newCtx, _ = codec.WithCloneMessage(ctx)
	// modify newCtx... 
	return next(ctx, req, rsp) // use origin ctx to next.
}
```

**Comment by Andrew-M-C** [comment]
Oh, I watched comment of WithCloneMessage and thought it will copy all KVs in the original message. So this is the bug of trpc instead of database?

The reason I use WithCloneMessage is because I need to dispatch another routine in the filter in some specific condition. I will use the original ctx to fix this.
