### ISSUE TITLE
kafka: Kafka tag error

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-ecosystem/go-database#31]
### What version of trpc-go-database are you using?

The latest tag of `trpc-database/kafka` was mistakenly specified as `1.1.0`. When executing `go get -u`, it is not recognized as latest release.

Please re-release kafka as `kafka/v1.1.0`

**Comment by WineChord** [comment]
https://github.com/trpc-ecosystem/go-database/releases/tag/kafka%2Fv1.1.0
